apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-news
  namespace: default
spec:
  schedule: "0 6 * * 5"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: raspberry-pi-news-fetcher
              image: henholm/raspberrypi3-debian-calibre:latest
              command: ["/bin/bash", "-c"]
              args: ["/app/scripts/fetch_news.sh --output-dir /app/fetched-news --sources-file /app/SOURCES 2>&1 | tee -a /app/logs/fetch_news.out"]
              volumeMounts:
                - name: raspberry-pi-news-fetcher
                  mountPath: /app
          restartPolicy: OnFailure
          volumes:
          - name: raspberry-pi-news-fetcher
            hostPath:
              path: /home/pi/devel/raspberry-pi-news-fetcher