apiVersion: batch/v1
# apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fetch-news
  namespace: default
spec:
  schedule: "0 6 * * 5"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rpi-news-fetcher
              image: henholm/raspberrypi3-debian-calibre:latest
              command: ["/bin/bash", "/app/scripts/fetch_news.sh", "--output-folder", "/app/fetched-news", "--sources-file", "/app/SOURCES", "2>&1", "|", "tee", "-a", "/app/logs/fetch_news.out"]
              volumeMounts:
                - name: rpi-news-fetcher
                  mountPath: /app
          restartPolicy: OnFailure
          volumes:
          - name: rpi-news-fetcher
            hostPath:
              path: /home/pi/devel/rpi-news-fetcher