apiVersion: batch/v1
# apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fetch-news
  namespace: default
spec:
  schedule: "0 6 * * 5"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rpi-books
              image: henholm/rpi-news-fetcher:latest
              command: ["/bin/bash", "/rpi-news-fetcher/scripts/fetch_news.sh", "--output-folder", "/rpi-news-fetcher/fetched-news", "--sources-file", "/rpi-news-fetcher/SOURCES", "2>&1", "|", "tee", "-a", "/rpi-news-fetcher/logs/fetch_news.out"]
              volumeMounts:
                - name: rpi-news-fetcher
                  mountPath: /rpi-news-fetcher
          restartPolicy: OnFailure
          volumes:
          - name: rpi-news-fetcher
            hostPath:
              path: /home/pi/devel/rpi-news-fetcher