name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-push-container-image:
    name: Build and Push Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Generate Docker Metadata
        id: generate-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.event.repository.name }}
          # Generate image tags based on the following events/attributes:
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      # Add support for more platforms with QEMU.
      - name: Set up QEMU
        id: set-up-qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: set-up-docker-buildx
        uses: docker/setup-buildx-action@v3

      - name: Log In to Docker Hub
        id: log-in-to-docker-hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        id: build-and-push-image
        uses: docker/build-push-action@v6
        with:
          # Build on feature branches / PRs, but push only if on the `main` branch.
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.generate-metadata.outputs.tags }}
          labels: ${{ steps.generate-metadata.outputs.labels }}
          platforms: linux/arm/v7
